### ISSUE TITLE
TOTP should support SHA256 and SHA512

### ISSUE THREAD

**Issue by TheBlueSky** [adalberht/hotp-totp-generator#1]
`totp` function does not provide the option to specify the hash function, while `hotp` function does.

As per the related RFCs ([RFC 4226](https://tools.ietf.org/html/rfc4226) and [RFC 6238](https://tools.ietf.org/html/rfc6238)), HOTP only uses SHA-1 while TOTP can optionally support SHA-256 and SHA-512.

This means that:

1. The default hash function should be SHA-1, because it is the only mandatory one and supported by both.
1. `totp` function parameter should have an extra property, `algorithm`, to specify the hash function.

If you'd like to, I can submit a pull request for it. But keep in mind that the change related to point number one is a breaking change.

**Comment by albertusdev** [comment]
Hello @TheBlueSky ,
First of all I would like to say thank you for opening an issue and offering to make a pull request. Sorry for the late reply. This is my first npm package too.
I have bumped the version to 1.1.0 now.

You are right, as per the related RFC HOTP should only support `SHA-1`. But because TOTP depends on HOTP, the `algorithm` params in HOTP should be retained.
I've changed the default algorithm to SHA-1 and add `algorithm` params to TOTP in 1.1.0.

Thank you very much!
